armor:
  - ==: me.Math0424.Withered.WitheredAPI.Serializable.DeployableSerializable
    name: "&aEliteShield"
    modelId: 3
    #types
    #SHIELD
    #PLAYER
    #HEAL
    type: SHIELD
    maxHealth: 1000.0
    range: 10.0
    deploySound: BLOCK_ANVIL_FALL
    deployPitch: 1
    deployVolume: 1
    level: 45
    chanceOfSpawning: 1.0