#syntax
#
#Material: -isBreakableByBullet
#
blocks:
  - BLUE_STAINED_GLASS_PANE: [true]
  - BROWN_STAINED_GLASS_PANE: [true]
  - CYAN_STAINED_GLASS_PANE: [true]
  - GRAY_STAINED_GLASS_PANE: [true]
  - GREEN_STAINED_GLASS_PANE: [true]
  - LIGHT_BLUE_STAINED_GLASS_PANE: [true]
  - LIGHT_GRAY_STAINED_GLASS_PANE: [true]
  - LIME_STAINED_GLASS_PANE: [true]
  - MAGENTA_STAINED_GLASS_PANE: [true]
  - ORANGE_STAINED_GLASS_PANE: [true]
  - PINK_STAINED_GLASS_PANE: [true]
  - PURPLE_STAINED_GLASS_PANE: [true]
  - RED_STAINED_GLASS_PANE: [true]
  - WHITE_STAINED_GLASS_PANE: [true]
  - YELLOW_STAINED_GLASS_PANE: [true]
  - BLACK_STAINED_GLASS_PANE: [true]
  - GLASS_PANE: [true]
  - BLUE_STAINED_GLASS: [true]
  - BROWN_STAINED_GLASS: [true]
  - CYAN_STAINED_GLASS: [true]
  - GRAY_STAINED_GLASS: [true]
  - GREEN_STAINED_GLASS: [true]
  - LIGHT_BLUE_STAINED_GLASS: [true]
  - LIGHT_GRAY_STAINED_GLASS: [true]
  - LIME_STAINED_GLASS: [true]
  - MAGENTA_STAINED_GLASS: [true]
  - ORANGE_STAINED_GLASS: [true]
  - PINK_STAINED_GLASS: [true]
  - PURPLE_STAINED_GLASS: [true]
  - RED_STAINED_GLASS: [true]
  - WHITE_STAINED_GLASS: [true]
  - YELLOW_STAINED_GLASS: [true]
  - BLACK_STAINED_GLASS: [true]