#syntax
#
#Material: -isRoadBlock -isBreakableByPlayer -isBreakableByBullet
#
ROSE_BUSH: [false, true, true]
FERN: [false, true, true]
DEAD_BUSH: [false, true, true]
SWEET_BERRY_BUSH: [false, true, true]
SUGAR_CANE: [false, true, true]
LARGE_FERN: [false, true, true]
GRASS: [false, true, true]
PEONY: [false, true, true]
LILAC: [false, true, true]
GLASS: [false, true, true]
TALL_GRASS: [false, true, true]
BLUE_STAINED_GLASS_PANE: [false, true, true]
BROWN_STAINED_GLASS_PANE: [false, true, true]
CYAN_STAINED_GLASS_PANE: [false, true, true]
GRAY_STAINED_GLASS_PANE: [false, true, true]
GREEN_STAINED_GLASS_PANE: [false, true, true]
LIGHT_BLUE_STAINED_GLASS_PANE: [false, true, true]
LIGHT_GRAY_STAINED_GLASS_PANE: [false, true, true]
LIME_STAINED_GLASS_PANE: [false, true, true]
MAGENTA_STAINED_GLASS_PANE: [false, true, true]
ORANGE_STAINED_GLASS_PANE: [false, true, true]
PINK_STAINED_GLASS_PANE: [false, true, true]
PURPLE_STAINED_GLASS_PANE: [false, true, true]
RED_STAINED_GLASS_PANE: [false, true, true]
WHITE_STAINED_GLASS_PANE: [false, true, true]
YELLOW_STAINED_GLASS_PANE: [false, true, true]
BLACK_STAINED_GLASS_PANE: [false, true, true]
GLASS_PANE: [false, true, true]
BLUE_STAINED_GLASS: [false, true, true]
BROWN_STAINED_GLASS: [false, true, true]
CYAN_STAINED_GLASS: [false, true, true]
GRAY_STAINED_GLASS: [false, true, true]
GREEN_STAINED_GLASS: [false, true, true]
LIGHT_BLUE_STAINED_GLASS: [false, true, true]
LIGHT_GRAY_STAINED_GLASS: [false, true, true]
LIME_STAINED_GLASS: [false, true, true]
MAGENTA_STAINED_GLASS: [false, true, true]
ORANGE_STAINED_GLASS: [false, true, true]
PINK_STAINED_GLASS: [false, true, true]
PURPLE_STAINED_GLASS: [false, true, true]
RED_STAINED_GLASS: [false, true, true]
WHITE_STAINED_GLASS: [false, true, true]
YELLOW_STAINED_GLASS: [false, true, true]
BLACK_STAINED_GLASS: [false, true, true]
COAL_BLOCK: [false, true, false]
AIR: [true, false, false]
STONE_BRICKS: [true, false, false]
CRACKED_STONE_BRICKS: [true, false, false]
MOSSY_STONE_BRICKS: [true, false, false]